litd {
  http {
    host = "0.0.0.0"
    port = 8080
  }

  mongodb {
#    uri = "mongodb://localhost:27017/?replicaSet=rs0"
    uri = "mongodb+srv://vancinad_db_user:Gen01:01-atlas@cluster0.pk90h5l.mongodb.net/?appName=Cluster0"
    database = "litd"
  }
}
