litd {
  http {
    host = "127.0.0.1"
    port = 8080
  }

  mongodb {
    # Default development values; override via env vars if needed
#    uri = "mongodb://localhost:27017"
#    database = "test"
    uri = ${LITD_DB_CONNECT_STRING}
    database = ${LITD_DB_DBNAME}
  }
}
